<!DOCTYPE html>
<html lang="en">
<head>
    <title>MVC - test</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="css/style.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="js/script.js"></script>
</head>
<body>

<?php
$isAuth = \App\Services\Auth\AuthManager::getInstance()->isAuth();
$class = $isAuth ? 'custom-nav-admin' : '';
?>
<nav class="navbar navbar-expand-lg navbar-light bg-light <?php echo $class?>">
    <a class="navbar-brand" href="/">MVC - test</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/tasks">List of tasks <span class="sr-only">(current)</span></a>
            </li>
            <?php if ($isAuth):?>
                <li class="nav-item active">
                    <a class="nav-link" href="/logout">(<?php echo \App\Services\Auth\AuthManager::getInstance()->getUser()->login?>) logout<span class="sr-only">(current)</span></a>
                </li>
            <?php else:?>
                <li class="nav-item active">
                    <a class="nav-link" href="/login">Login<span class="sr-only">(current)</span></a>
                </li>
            <?php endif;?>

        </ul>
    </div>
</nav>

<div class="container" style="margin-top: 30px">
    <?php echo $content?>
</div>

</body>
</html>