<form action="/login-send" method="post">
    <div class="form-group">
        <label>Login</label>
        <input type="text" max="20" class="form-control" placeholder="Enter login" name="login">
    </div>

    <div class="form-group">
        <label>Password</label>
        <input type="password" max="20" class="form-control" placeholder="Enter Password" name="password">
    </div>

    <?php if ($error):?>
        <div class="alert alert-danger">
            <?php echo $error?>
        </div>
    <?php endif;?>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>