<form action="<?php echo $formAction?>" method="post">
    <div class="form-group">
        <label>User name</label>
        <input type="text" max="20" class="form-control" placeholder="Enter user name" name="username">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description of task</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" name="text"></textarea>
    </div>

    <?php if (\App\Services\Auth\AuthManager::getInstance()->isAuth()):?>
        <div class="form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="1" <?php if ($task->isCompletedTask):?>checked<?php endif;?> name="isCompleted">Is completed?
            </label>
        </div>
    <?php endif;?>

    <input type="hidden" name="taskId" value="<?php echo $task->id?>">
    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>